import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type JsonSchemaNode = {
  properties?: {
    type?: {
      const?: string;
    };
  };
  required?: string[];
};

type ArchflowJsonSchema = {
  definitions?: {
    archflow?: {
      properties?: {
        nodes?: {
          items?: {
            anyOf?: JsonSchemaNode[];
          };
        };
      };
    };
  };
};

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(repoRoot, "public", "llms-full.txt");
const cookbookDir = join(repoRoot, "docs", "cookbook");
const examplesDir = join(repoRoot, "src", "examples");
const cookbookSlugs = [
  "01-ecommerce",
  "02-microservices-async",
  "03-api-gateway",
  "04-k8s-autoscaling",
  "05-event-driven",
];

function readProjectFile(path: string): string {
  return readFileSync(join(repoRoot, path), "utf8").trimEnd();
}

function schemaSummary(): string {
  const schema = JSON.parse(readProjectFile("public/schema/archflow.schema.json")) as ArchflowJsonSchema;
  const nodeSchemas = schema.definitions?.archflow?.properties?.nodes?.items?.anyOf ?? [];
  const rows = nodeSchemas
    .map((node) => {
      const type = node.properties?.type?.const;
      const required = node.required?.join(", ");
      if (!type || !required) {
        return undefined;
      }
      return `- \`${type}\`: ${required}`;
    })
    .filter((row): row is string => Boolean(row));

  return [
    "# Compact JSON Schema reference",
    "",
    "Schema URL: https://example.com/archflow/schema/archflow.schema.json",
    "",
    "Required fields by node `type`:",
    "",
    ...rows,
  ].join("\n");
}

function cookbookDocsWithYaml(): string {
  return cookbookSlugs
    .map((slug) => {
      const docPath = join(cookbookDir, `${slug}.md`);
      const yamlPath = join(examplesDir, `${slug}.yaml`);
      const doc = readFileSync(docPath, "utf8").trimEnd();
      const yaml = readFileSync(yamlPath, "utf8").trimEnd();
      return `${doc}\n\n## YAML\n\n\`\`\`yaml\n${yaml}\n\`\`\``;
    })
    .join("\n\n---\n\n");
}

function assertCookbookFilesExist(): void {
  const docFiles = new Set(readdirSync(cookbookDir));
  const yamlFiles = new Set(readdirSync(examplesDir));
  for (const slug of cookbookSlugs) {
    if (!docFiles.has(`${slug}.md`)) {
      throw new Error(`Missing cookbook doc: ${slug}.md`);
    }
    if (!yamlFiles.has(`${slug}.yaml`)) {
      throw new Error(`Missing cookbook YAML: ${slug}.yaml`);
    }
  }
}

assertCookbookFilesExist();

const sections = [
  "# archflow llms-full.txt",
  "",
  "Generated by `npm run llms:gen` from README.md, the public JSON Schema, cookbook docs, and cookbook YAML examples.",
  "",
  "---",
  "",
  readProjectFile("README.md"),
  "",
  "---",
  "",
  schemaSummary(),
  "",
  "---",
  "",
  "# Cookbook docs and YAML examples",
  "",
  cookbookDocsWithYaml(),
];

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${sections.join("\n")}\n`);
